# -*- coding: utf-8 -*-
"""Dissertation .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hbp3ftOlIgcQOadC2rm1PWpRiJ3DHcz1
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import os

def process_aqi_file(file_name):

    parts = file_name.replace(".xlsx", "").split("_")

    # Find year (last number in filename)
    year = None
    for part in parts:
        if part.isdigit() and len(part) == 4:
            year = int(part)

    # Find city (just before year)
    city = None
    for i, part in enumerate(parts):
        if part.isdigit() and len(part) == 4:
            city = parts[i-1].capitalize()
            break

    if year is None or city is None:
        raise ValueError("City or Year not found in filename")

    df = pd.read_excel(file_name)

    df.rename(columns={df.columns[0]: "Day"}, inplace=True)

    df_long = df.melt(id_vars=["Day"], var_name="Month", value_name="AQI")

    df_long = df_long.dropna()

    df_long["Month"] = pd.to_datetime(df_long["Month"], format='%B').dt.month

    df_long["date"] = pd.to_datetime(
        df_long["Day"].astype(str) + "-" +
        df_long["Month"].astype(str) + "-" +
        str(year),
        format="%d-%m-%Y",
        errors='coerce'
    )

    df_long["city"] = city

    return df_long[["date", "city", "AQI"]]

all_dfs = []

for file_name in uploaded.keys():
    if file_name.endswith(".xlsx"):
        try:
            df_temp = process_aqi_file(file_name)
            all_dfs.append(df_temp)
            print(f"Processed: {file_name}")
        except Exception as e:
            print(f"Skipped {file_name}: {e}")

# Check before concat
if len(all_dfs) == 0:
    print("No valid files processed!")
else:
    df_final = pd.concat(all_dfs, ignore_index=True)

all_dfs = []

for file_name in uploaded.keys():
    if file_name.endswith(".xlsx"):
        try:
            df_temp = process_aqi_file(file_name)
            all_dfs.append(df_temp)
            print(f"Processed: {file_name}")
        except Exception as e:
            print(f"Skipped {file_name}: {e}")

# Check before concat
if len(all_dfs) == 0:
    print("No valid files processed!")
else:
    df_final = pd.concat(all_dfs, ignore_index=True)

df_final.to_csv("final_aqi_2020_2025.csv", index=False)

from google.colab import files
files.download("final_aqi_2020_2025.csv")

df_final

"""## Data Exploration and Visualization"""

print(df_final.info())
display(df_final.describe())

# Drop rows where 'date' is NaT
df_final_cleaned = df_final.dropna(subset=['date', 'AQI']).copy()

# Convert AQI to numeric, coercing errors
df_final_cleaned['AQI'] = pd.to_numeric(df_final_cleaned['AQI'], errors='coerce')

# Drop rows where AQI is NaN after conversion
df_final_cleaned.dropna(subset=['AQI'], inplace=True)

# Ensure date is datetime type
df_final_cleaned['date'] = pd.to_datetime(df_final_cleaned['date'])

print(df_final_cleaned.info())
display(df_final_cleaned.head())

"""### Average AQI by Year (Bar Chart)"""

import matplotlib.pyplot as plt
import seaborn as sns

# Extract year from date
df_final_cleaned['year'] = df_final_cleaned['date'].dt.year

# Calculate average AQI per year
avg_aqi_per_year = df_final_cleaned.groupby('year')['AQI'].mean().reset_index()

plt.figure(figsize=(10, 6))
sns.barplot(x='year', y='AQI', data=avg_aqi_per_year, palette='viridis')
plt.title('Average AQI by Year')
plt.xlabel('Year')
plt.ylabel('Average AQI')
plt.ylim(80, avg_aqi_per_year['AQI'].max() * 1.1)  # Adjust y-axis to start from 80
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Calculate monthly average AQI for each city
df_final_cleaned['month_name'] = df_final_cleaned['date'].dt.strftime('%b')
df_monthly_avg = df_final_cleaned.groupby(['city', 'month_name']).agg(monthly_avg_AQI=('AQI', 'mean')).reset_index()

# Define the order of months for plotting
month_order = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
]

# Convert 'month_name' to a categorical type with the specified order
df_monthly_avg['month_name'] = pd.Categorical(df_monthly_avg['month_name'], categories=month_order, ordered=True)

# Sort by month for correct plotting order
df_monthly_avg = df_monthly_avg.sort_values(by=['city', 'month_name'])

plt.figure(figsize=(15, 8))
sns.lineplot(data=df_monthly_avg, x='month_name', y='monthly_avg_AQI', hue='city', marker='o', palette='tab10')
plt.title('Average Monthly AQI by City')
plt.xlabel('Month')
plt.ylabel('Average AQI')
plt.legend(title='City', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True)
plt.tight_layout()
plt.show()

"""### Heatmap of Average AQI by City and Month"""

# Extract month from date
df_final_cleaned['month_name'] = df_final_cleaned['date'].dt.strftime('%b')

# Calculate average AQI per city and month
aqi_heatmap_data = df_final_cleaned.groupby(['city', 'month_name'])['AQI'].mean().unstack()

# Ensure months are in chronological order for plotting
month_order = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
]
aqi_heatmap_data = aqi_heatmap_data.reindex(columns=month_order, fill_value=0)

# Generate the heatmap
plt.figure(figsize=(14, 8))
sns.heatmap(aqi_heatmap_data, annot=True, fmt=".0f", cmap="Blues", linewidths=.5)
plt.title('Average AQI by City and Month')
plt.xlabel('Month')
plt.ylabel('City')
plt.show()

"""## Machine Learning Model for AQI Prediction

Preparation of the data for a machine learning model to predict future AQI values. We will perform feature engineering, split the data, train a RandomForestRegressor, and evaluate its performance.
"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder

# Feature Engineering
df_final_ml = df_final_cleaned.copy()

# Filter data to use only till February 2025 for training
df_final_ml = df_final_ml[df_final_ml['date'] <= '2025-02-28'].copy()

df_final_ml['year'] = df_final_ml['date'].dt.year
df_final_ml['month'] = df_final_ml['date'].dt.month
df_final_ml['day'] = df_final_ml['date'].dt.day
df_final_ml['dayofweek'] = df_final_ml['date'].dt.dayofweek

# Encode 'city' feature
le = LabelEncoder()
df_final_ml['city_encoded'] = le.fit_transform(df_final_ml['city'])

# Define features (X) and target (y)
X = df_final_ml[['year', 'month', 'day', 'dayofweek', 'city_encoded']]
y = df_final_ml['AQI']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a RandomForestRegressor model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse:.2f}')
print(f'R-squared: {r2:.2f}')

# Display feature importances
feature_importances = pd.Series(model.feature_importances_, index=X.columns).sort_values(ascending=False)
print('\nFeature Importances:')
print(feature_importances)

"""### Improving Model Performance: Feature Engineering"""

# Feature Engineering - Adding more temporal features
df_final_ml_enriched = df_final_cleaned.copy()
df_final_ml_enriched = df_final_ml_enriched[df_final_ml_enriched['date'] <= '2025-02-28'].copy()

df_final_ml_enriched['year'] = df_final_ml_enriched['date'].dt.year
df_final_ml_enriched['month'] = df_final_ml_enriched['date'].dt.month
df_final_ml_enriched['day'] = df_final_ml_enriched['date'].dt.day
df_final_ml_enriched['dayofweek'] = df_final_ml_enriched['date'].dt.dayofweek
df_final_ml_enriched['dayofyear'] = df_final_ml_enriched['date'].dt.dayofyear
df_final_ml_enriched['weekofyear'] = df_final_ml_enriched['date'].dt.isocalendar().week.astype(int)
df_final_ml_enriched['quarter'] = df_final_ml_enriched['date'].dt.quarter
df_final_ml_enriched['is_month_start'] = df_final_ml_enriched['date'].dt.is_month_start.astype(int)
df_final_ml_enriched['is_month_end'] = df_final_ml_enriched['date'].dt.is_month_end.astype(int)

# Encode 'city' feature using the already fitted LabelEncoder
df_final_ml_enriched['city_encoded'] = le.transform(df_final_ml_enriched['city'])

# Define features (X_enriched) and target (y)
X_enriched = df_final_ml_enriched[['year', 'month', 'day', 'dayofweek', 'dayofyear', 'weekofyear', 'quarter', 'is_month_start', 'is_month_end', 'city_encoded']]
y_enriched = df_final_ml_enriched['AQI']

# Split data into training and testing sets
X_train_enriched, X_test_enriched, y_train_enriched, y_test_enriched = train_test_split(X_enriched, y_enriched, test_size=0.2, random_state=42)

print("New features created and data split for enriched model.")
print(f"Number of features in enriched dataset: {X_enriched.shape[1]}")
display(X_enriched.head())

"""### Re-training RandomForest Regressor with Enriched Features

"""

# Train a RandomForestRegressor model with enriched features
model_enriched = RandomForestRegressor(n_estimators=100, random_state=42)
model_enriched.fit(X_train_enriched, y_train_enriched)

# Make predictions on the test set
y_pred_enriched = model_enriched.predict(X_test_enriched)

# Evaluate the model
mse_enriched = mean_squared_error(y_test_enriched, y_pred_enriched)
r2_enriched = r2_score(y_test_enriched, y_pred_enriched)

print(f'RandomForest (Enriched Features) Mean Squared Error: {mse_enriched:.2f}')
print(f'RandomForest (Enriched Features) R-squared: {r2_enriched:.2f}')

# Display feature importances for the enriched model
feature_importances_enriched = pd.Series(model_enriched.feature_importances_, index=X_enriched.columns).sort_values(ascending=False)
print('Feature Importances (Enriched RandomForest Model):')
print(feature_importances_enriched)

"""### Predicting with the Enriched RandomForest Model and Comparing to Actuals (March 5, 2025)"""

import datetime
import pandas as pd # Ensure pandas is imported as 'pd'

# Example future date for prediction
future_date = datetime.datetime(2025, 3, 5) # Changed to March 5, 2025

# Get actual AQI data for March 5, 2025
actual_aqi_march_5 = df_final_cleaned[
    (df_final_cleaned['date'].dt.year == 2025) &
    (df_final_cleaned['date'].dt.month == 3) &
    (df_final_cleaned['date'].dt.day == 5)
][['city', 'AQI']].rename(columns={'AQI': 'actual_AQI', 'city': 'city_name'})

# Group by city_name and take the mean to handle potential duplicates for a given city on the same day
actual_aqi_march_5 = actual_aqi_march_5.groupby('city_name')['actual_AQI'].mean().reset_index()

# Create a DataFrame for future predictions using the enriched features
future_predictions_data_enriched = []

for city in df_final_ml_enriched['city'].unique():
    city_encoded_val = le.transform([city])[0]
    future_predictions_data_enriched.append({
        'year': future_date.year,
        'month': future_date.month,
        'day': future_date.day,
        'dayofweek': future_date.weekday(),
        'dayofyear': future_date.timetuple().tm_yday,
        'weekofyear': pd.to_datetime(future_date).isocalendar().week,
        'quarter': pd.to_datetime(future_date).quarter,
        'is_month_start': int(pd.to_datetime(future_date).is_month_start),
        'is_month_end': int(pd.to_datetime(future_date).is_month_end),
        'city_encoded': city_encoded_val,
        'city_name': city
    })

future_df_enriched = pd.DataFrame(future_predictions_data_enriched)

# Define the features for prediction, matching X_enriched's columns
future_X_enriched = future_df_enriched[['year', 'month', 'day', 'dayofweek', 'dayofyear', 'weekofyear', 'quarter', 'is_month_start', 'is_month_end', 'city_encoded']]

# Make predictions using the enriched model
future_df_enriched['predicted_AQI_enriched'] = model_enriched.predict(future_X_enriched)

# Merge predicted (Enriched RandomForest) and actual data (actual_aqi_march_5 is already available)
comparison_df_enriched = pd.merge(
    future_df_enriched[['city_name', 'predicted_AQI_enriched']],
    actual_aqi_march_5,
    on='city_name',
    how='left'
)

# Calculate the difference for the enriched model
comparison_df_enriched['difference_enriched'] = comparison_df_enriched['predicted_AQI_enriched'] - comparison_df_enriched['actual_AQI']

print(f'Predicted AQI for {future_date.strftime("%Y-%m-%d")} using Enriched RandomForest Model:')
display(comparison_df_enriched.set_index('city_name'))

"""### Residual Error Analysis by City (March 5, 2025) - Enriched RandomForest Model

visualization of the residual errors for the enriched RandomForest model for March 5, 2025.
"""

plt.figure(figsize=(14, 7))
sns.barplot(x='city_name', y='difference_enriched', data=comparison_df_enriched.sort_values(by='difference_enriched', ascending=False), palette='viridis')
plt.title('Residual Errors (Predicted - Actual AQI) for March 5, 2025 by City (Enriched RandomForest)')
plt.xlabel('City')
plt.ylabel('Prediction Error (Predicted AQI - Actual AQI)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.axhline(0, color='black', linestyle='--', linewidth=0.8) # Add a line at zero for reference
plt.tight_layout()
plt.show()

"""### Comparing MAE of RandomForest Models for March 5, 2025"""

from sklearn.metrics import mean_absolute_error
import pandas as pd
import datetime

future_date = datetime.datetime(2025, 3, 5)

# Create a DataFrame for future predictions using the original model (basic features)
future_predictions_data = []
for city in df_final_ml['city'].unique(): # df_final_ml and le should be available from previous executions
    city_encoded_val = le.transform([city])[0]
    future_predictions_data.append({
        'year': future_date.year,
        'month': future_date.month,
        'day': future_date.day,
        'dayofweek': future_date.weekday(),
        'city_encoded': city_encoded_val,
        'city_name': city
    })

future_df = pd.DataFrame(future_predictions_data)

# Define the features for prediction, matching X's columns
future_X = future_df[['year', 'month', 'day', 'dayofweek', 'city_encoded']]

# Make predictions using the basic RandomForest model (model should be available)
future_df['predicted_AQI'] = model.predict(future_X)

# Create the comparison_df for the basic RandomForest model
comparison_df = pd.merge(
    future_df[['city_name', 'predicted_AQI']],
    actual_aqi_march_5,
    on='city_name',
    how='left'
)
comparison_df['difference'] = comparison_df['predicted_AQI'] - comparison_df['actual_AQI']

# Now, proceed with the original merge of both comparison dataframes
final_comparison_df = pd.merge(
    comparison_df[['city_name', 'predicted_AQI', 'actual_AQI']], # Original RandomForest
    comparison_df_enriched[['city_name', 'predicted_AQI_enriched']], # comparison_df_enriched should be available
    on='city_name',
    how='left'
)

# Drop rows where actual_AQI is NaN (cities for which we don't have actuals for March 5)
final_comparison_df.dropna(subset=['actual_AQI'], inplace=True)

# Calculate MAE for each model for March 5, 2025
mae_rf_march5 = mean_absolute_error(final_comparison_df['actual_AQI'], final_comparison_df['predicted_AQI'])
mae_rf_enriched_march5 = mean_absolute_error(final_comparison_df['actual_AQI'], final_comparison_df['predicted_AQI_enriched'])

print(f'MAE for March 5, 2025 (RandomForest - Basic Features): {mae_rf_march5:.2f}')
print(f'MAE for March 5, 2025 (RandomForest - Enriched Features): {mae_rf_enriched_march5:.2f}')

# Get actual AQI data for March 5, 2025
actual_aqi_march_5 = df_final_cleaned[
    (df_final_cleaned['date'].dt.year == 2025) &
    (df_final_cleaned['date'].dt.month == 3) &
    (df_final_cleaned['date'].dt.day == 5)
][['city', 'AQI']].rename(columns={'AQI': 'actual_AQI', 'city': 'city_name'})

# Group by city_name and take the mean to handle potential duplicates for a given city on the same day
actual_aqi_march_5 = actual_aqi_march_5.groupby('city_name')['actual_AQI'].mean().reset_index()

"""### Mean Absolute Error (MAE) for RandomForest Models"""

from sklearn.metrics import mean_absolute_error

# Calculate MAE for RandomForest (basic features)
mae_rf = mean_absolute_error(y_test, y_pred)
print(f'RandomForest (Basic Features) Mean Absolute Error: {mae_rf:.2f}')

# Calculate MAE for RandomForest (enriched features)
mae_rf_enriched = mean_absolute_error(y_test_enriched, y_pred_enriched)
print(f'RandomForest (Enriched Features) Mean Absolute Error: {mae_rf_enriched:.2f}')

from google.colab import files
uploaded = files.upload()

import pandas as pd

pm10 = pd.read_csv('PM 10.csv')
so2 = pd.read_csv('SO 2.csv')
no2 = pd.read_csv('NO 2.csv')
pm25 = pd.read_csv('PM 2.5 .csv')

so2

def convert_to_median(value):
    if isinstance(value, str):
        value = value.replace('–', '-')

        if '-' in value:
            low, high = value.split('-')
            return (float(low) + float(high)) / 2

        return float(value)

    return value

years = ['2019', '2021', '2022', '2023']

for year in years:
    so2[year] = so2[year].apply(convert_to_median)

so2_long = so2.melt(id_vars=['City'],
                    value_vars=years,
                    var_name='year',
                    value_name='so2')

so2_long['year'] = so2_long['year'].astype(int)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))

for city in so2_long['City'].unique():
    city_data = so2_long[so2_long['City'] == city]
    plt.plot(city_data['year'], city_data['so2'], marker='o', label=city)

plt.title('SO2 Levels Trend (2019–2023)')
plt.xlabel('Year')
plt.ylabel('SO2 Level')

plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()

plt.show()

so2

so2['2019'] = so2['2019'].apply(convert_to_median)
display(so2.head())

years = ['2019', '2021', '2022', '2023']
so2_long = so2.melt(id_vars=['City'],
                    value_vars=years,
                    var_name='year',
                    value_name='so2')

so2_long['year'] = so2_long['year'].astype(int)

print("SO2 DataFrame converted to long format and 'year' column converted to integer:")
display(so2_long.head())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 8))
sns.barplot(x='City', y='so2', hue='year', data=so2_long, palette='viridis')
plt.title('SO2 Levels by City (2019, 2021-2023)')
plt.xlabel('City')
plt.ylabel('SO2 Level')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Year', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

no2

import pandas as pd
import matplotlib.pyplot as plt

# 🔹 Step 1: Clean column names
no2.columns = no2.columns.str.strip()

# 🔹 Step 2: Function to handle ranges (like 7–11)
def convert_to_median(value):
    if isinstance(value, str):
        value = value.replace('–', '-')  # fix special dash

        if '-' in value:
            low, high = value.split('-')
            return (float(low) + float(high)) / 2

        return float(value)

    return value

# 🔹 Step 3: Apply cleaning to all years
years = ['2019', '2021', '2022', '2023']

for year in years:
    no2[year] = no2[year].apply(convert_to_median)

# 🔹 Step 4: Convert wide → long format
no2_long = no2.melt(id_vars=['City'],
                    value_vars=years,
                    var_name='year',
                    value_name='no2')

# 🔹 Step 5: Convert year to integer
no2_long['year'] = no2_long['year'].astype(int)

# 🔹 Step 6: LINE CHART (Trend)
plt.figure(figsize=(10,6))

for city in no2_long['City'].unique():
    city_data = no2_long[no2_long['City'] == city]
    plt.plot(city_data['year'], city_data['no2'], marker='o', label=city)

plt.title('NO2 Levels Trend (2019–2023)')
plt.xlabel('Year')
plt.ylabel('NO2 Level')

plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

# 🔹 Step 7: BAR CHART (City comparison)
pivot = no2_long.pivot(index='City', columns='year', values='no2')

pivot.plot(kind='bar', figsize=(12,6))

plt.title('NO2 Levels by City (All Years)')
plt.xlabel('City')
plt.ylabel('NO2 Level')
plt.xticks(rotation=45)

plt.show()

pm25

pm25_cleaned_header = pd.read_csv('PM 2.5 .csv', header=1, skiprows=[0])

pm25_cleaned_header.columns = pm25_cleaned_header.columns.str.strip()

years = ['2019', '2021', '2022', '2023']

for year in years:
    if year in pm25_cleaned_header.columns:
        pm25_cleaned_header[year] = pm25_cleaned_header[year].apply(convert_to_median)

pm25_cleaned_header.drop(columns=['2019'], inplace=True, errors='ignore')

display(pm25_cleaned_header.head())

"""**Reasoning**:
I need to reload the `pm25` DataFrame with the correct header, clean column names, apply the `convert_to_median` function to specified year columns, and then drop the '2019' column as per the instructions.


"""

pm25 = pd.read_csv('PM 2.5 .csv', header=1)

pm25.columns = pm25.columns.str.strip()

years_to_process = ['2019', '2021', '2022', '2023']

for year in years_to_process:
    if year in pm25.columns:
        pm25[year] = pm25[year].apply(convert_to_median)

pm25.drop(columns=['2019'], inplace=True, errors='ignore')

print("PM2.5 DataFrame cleaned and '2019' column dropped:")
display(pm25.head())

years_for_long_format = ['2021', '2022', '2023']
pm25_long = pm25.melt(id_vars=['City'],
                      value_vars=years_for_long_format,
                      var_name='year',
                      value_name='pm25')

# Convert 'year' column to integer type
pm25_long['year'] = pm25_long['year'].astype(int)

print("PM2.5 DataFrame converted to long format:")
display(pm25_long.head())

"""**Reasoning**:
The next step is to visualize the PM2.5 trends over the years 2021-2023 for each city using a line chart, as outlined in the subtask.


"""

import matplotlib.pyplot as plt
import seaborn as sns

# Visualize PM2.5 Trends (Line Chart)
plt.figure(figsize=(12, 7))
for city in pm25_long['City'].unique():
    city_data = pm25_long[pm25_long['City'] == city]
    plt.plot(city_data['year'], city_data['pm25'], marker='o', label=city)

plt.title('PM2.5 Levels Trend (2021–2023)')
plt.xlabel('Year')
plt.ylabel('PM2.5 Level (µg/m³)')
plt.xticks([2021, 2022, 2023]) # Ensure only the relevant years are shown as ticks
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Visualize PM2.5 City Comparison (Bar Chart)
plt.figure(figsize=(14, 8))
sns.barplot(x='City', y='pm25', hue='year', data=pm25_long, palette='viridis')
plt.title('PM2.5 Levels by City (2021–2023)')
plt.xlabel('City')
plt.ylabel('PM2.5 Level (µg/m³)')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Year', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()